In [1]:
print('hello world')

hello world


In [13]:
print("This line will be printed")

This line will be printed


In [4]:
x=1
if x==1:
    print('X is 1')

X is 1


In [7]:
hello = ("Hello" + " ")* 10
print(hello)

Hello Hello Hello Hello Hello Hello Hello Hello Hello Hello 


In [9]:
numbers = [1,2,3]
print(numbers*3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [16]:
name = "John"
print("%s, Hello!" %name)

John, Hello!


In [17]:
name = "John"
age = 23
print("%s is %d years old." %(name,age))

John is 23 years old.


In [21]:
data = ("John", "Doe", 53.44)
format_string = "Hello %s %s. Your current balance is $%s"
print(format_string %data)

Hello John Doe. Your current balance is $53.44


In [68]:
astring = "Hello world!"
print(astring.index("o"))
print(astring.count("o"))
print(len(astring))
print(astring[0])
print(astring[0:1])
print(astring[3:7])
print(astring[-6:11])
print(astring[3:7:2])
print(astring[::-1])

4
2
12
H
H
lo w
world
l 
!dlrow olleH


In [67]:
astring = "Hello world!"
print(astring.startswith("Hello"))
print(astring.endswith("world!"))

True
True


In [71]:
name = "John"
age = 23
if name == "John" and age == 23:
    print("Your name is %s, and you are %d years old." %(name,age))
if name in ["John", "Rick"]:
    print("Your name is either John or Rick.")

Your name is John, and you are 23 years old.
Your name is either John or Rick.


In [75]:
for x in range(3, 8, 3):
    print(x)

3
6


In [83]:
# Prints out 0,1,2,3,4

count = 0
while True:
    print(count)
    count += 1
    if count >= 5:
        break

# Prints out only odd numbers - 1,3,5,7,9
for x in range(10):
    # Check if x is even
    if x % 2 == 0:
        continue
    print(x)

0
1
2
3
4
1
3
5
7
9


In [93]:
numbers = [
    951, 402, 984, 651, 360, 69, 408, 319, 601, 485, 980, 507, 725, 547, 544,
    615, 83, 165, 141, 501, 263, 617, 865, 575, 219, 390, 984, 592, 236, 105, 942, 941,
    386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345,
    399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217,
    815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717,
    958, 609, 842, 451, 688, 753, 854, 685, 93, 857, 440, 380, 126, 721, 328, 753, 470,
    743, 527
]

# your code goes here
for number in numbers:
    if (number>237) & (number%2==0):
        print(number)

402
984
360
408
980
544
390
984
592
942
386
462
418
344
566
978
328
758
918
412
566
826
248
866
950
626
512
892
894
742
958
842
688
854
440
380
328
470


In [94]:
# Modify this function to return a list of strings as defined above
def list_benefits():
    return "More organized code", "More readable code", "Easier code reuse", "Allowing programmers to share and connect code together"

# Modify this function to concatenate to each benefit - " is a benefit of functions!"
def build_sentence(benefit):
    return "%s is a benefit of functions!" % benefit


def name_the_benefits_of_functions():
    list_of_benefits = list_benefits()
    for benefit in list_of_benefits:
        print(build_sentence(benefit))

name_the_benefits_of_functions()

More organized code is a benefit of functions!
More readable code is a benefit of functions!
Easier code reuse is a benefit of functions!
Allowing programmers to share and connect code together is a benefit of functions!


In [1]:
# define the Vehicle class
class Vehicle:
    name = ""
    kind = "car"
    color = ""
    value = 100.00
    def description(self):
        desc_str = "%s is a %s %s worth $%.2f." % (self.name, self.color, self.kind, self.value)
        return desc_str

# your code goes here
car1 = Vehicle()
car1.name = "Fer"
car1.color = "red"
car1.kind = "convertible"
car1.value = 60000.00

car2 = Vehicle()
car2.name = "Jump"
car2.color = "blue"
car2.kind = "van"
car2.value = 10000.00

# test code
print(car1.description())
print(car2.description())

Fer is a red convertible worth $60000.00.
Jump is a blue van worth $10000.00.


In [2]:
phonebook = {
    "John" : 938477566,
    "Jack" : 938377264,
    "Jill" : 947662781
}

# write your code here
phonebook["Jake"] = 938273443
del phonebook["Jill"]

# testing code
if "Jake" in phonebook:
    print("Jake is listed in the phonebook.")
if "Jill" not in phonebook:
    print("Jill is not listed in the phonebook.")

Jake is listed in the phonebook.
Jill is not listed in the phonebook.


In [3]:
import re

# Your code goes here
find_members = []
for member in dir(re):
    if "find" in member:
        find_members.append(member)

print(sorted(find_members))

['findall', 'finditer']


In [3]:
# Create 2 new lists height and weight
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]


print(type(height))
# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)
print(type(np_height))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
x = np.array([[1, 1, 1], [10,2, 3], [11, 111, 2]])

In [5]:
x

array([[  1,   1,   1],
       [ 10,   2,   3],
       [ 11, 111,   2]])

In [6]:
x.shape

(3, 3)

In [7]:
y = np.array([[1, 1, 1], [10,2, 3], [11, 111, 2]])

In [8]:
y

array([[  1,   1,   1],
       [ 10,   2,   3],
       [ 11, 111,   2]])

In [9]:
z = np.matmul(x, y)

In [10]:
z

array([[  22,  114,    6],
       [  63,  347,   22],
       [1143,  455,  348]])

In [11]:
z.T

array([[  22,   63, 1143],
       [ 114,  347,  455],
       [   6,   22,  348]])

In [12]:
z.T[0, 1]

63

In [13]:
z[0,1]

114

In [14]:
x = [1, 2, 3, 4, 5, 6, 7]

In [15]:
x

[1, 2, 3, 4, 5, 6, 7]

In [16]:
print(x)

[1, 2, 3, 4, 5, 6, 7]


In [17]:
y = (1 for i in range(10))

In [18]:
y

<generator object <genexpr> at 0x000001F4DFE548C8>

In [19]:
print(y)

<generator object <genexpr> at 0x000001F4DFE548C8>


In [20]:
for i in y:

SyntaxError: unexpected EOF while parsing (<ipython-input-20-39b32821c5a4>, line 1)

In [21]:
for i in y:
    print(i)

1
1
1
1
1
1
1
1
1
1


In [22]:
y

<generator object <genexpr> at 0x000001F4DFE548C8>

In [23]:
for i in y:
    print(i)

In [24]:
for i in x:
    print(i)

1
2
3
4
5
6
7


In [25]:
for i in x:
    print(i)

1
2
3
4
5
6
7


In [26]:
f = []
for i in range(10):
    f.append(i)

In [27]:
f

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
c = [i for i in range(10)]

In [29]:
c

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
set(c)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [31]:
x=[1,21,1]

In [32]:
set(x)

{1, 21}

In [34]:
set(x).union(set([1,20]))

{1, 20, 21}

In [35]:
x = {'name': 'Pranay', 'class': 12}

In [36]:
x

{'name': 'Pranay', 'class': 12}

In [44]:
import json
with open('file.json', 'w') as jsonfile:
    json.dump(x, jsonfile)

In [45]:
with open('file.json', 'r') as jsonfile:
    g = json.load(jsonfile)

In [46]:
g

{'name': 'Pranay', 'class': 12}

In [50]:
x = [1, 2]
import pickle


with open('file.pkl', 'wb') as picklefile:
    pickle.dump(x, picklefile)

In [5]:
x = float(input("Enter a number: "))
y = x//10
z = x/10
print("Y is: %f" %y)
print("Z is: %f" %z)

Enter a number: 100.2
Y is: 10.000000
Z is: 10.020000
